### ISSUE TITLE
How to delete multiple torrents with data?

### ISSUE THREAD

**Issue by asakura42** [tremc/tremc#102]
I found this line in source code: 
https://github.com/tremc/tremc/blob/f5ecc59aae16107c9538f86eeb163187271aad47/tremc#L257

But how to bind for example Y to delete multiple selected torrents?

**Comment by MatanZ** [comment]
In the config file (~/.config/tremc/settings.cfg by default) you add a section with a line:

`[ListKeys]`
`Y = remove_selected_data`

**Comment by asakura42** [comment]
Thank you! And thank you for such nice program too.
