### ISSUE TITLE
Division by 0 when viewing chunks of empty torrent

### ISSUE THREAD

**Issue by Leviticoh** [tremc/tremc#103]
when seeing chunks of a torrent added via magnet link with no peers tremc crashes reporting in stderr "ZeroDivisionError: division by zero"

i made a patch to fix this but i don't really know how to use git, what should i do to submit it?

**Comment by gangelop** [comment]
I've been aware of this issue and have been too lazy to report it (let alone fix it!). So, thanks!

**Comment by Leviticoh** [comment]
so, how do i submit it?
do i have to make a branch with the fix and then a pull request?

**Comment by gangelop** [comment]
Yes please!

**Comment by gangelop** [comment]
fixed in #104
