### ISSUE TITLE
incorrect seeds and leeches

### ISSUE THREAD

**Issue by jedi2610** [tremc/tremc#105]
![image](https://user-images.githubusercontent.com/30691152/110964895-b1129a80-8379-11eb-89b8-913711d36d88.png)

seeds and leeches are incorrect(see avengers endgame)

**Comment by MatanZ** [comment]
I do not see anything wrong. Can you provide more details of the problem?

**Comment by jedi2610** [comment]
the seeds and leachers in the web client is different from that displayed by `tremc`

**Comment by MatanZ** [comment]
I don't see numbers of seeds or leeches in the image. It might help if you will be a bit less terse.

If you mean number of peers (76 in your image), then it measures something else then the numbers of seeds and leeches in tremc. 

tremc shows number of seeds and leeches known to the trackers. The web interface shows the number of peers that are actually connected. If you will make the window wider (or select narrow screen mode), you will also see this number in the tremc display.

**Comment by jedi2610** [comment]
okay cool thanks, my bad. I'll close this issue.
