### ISSUE TITLE
24 hour format in torrent overview

### ISSUE THREAD

**Issue by ilf** [tremc/tremc#113]
In tremc 0.9.2, Torrent -> Overview shows this:

```
     Created: 12/31/2021 01:23:45 PM (6 weeks ago)
       Added: 12/31/2021 01:23:45 PM (6 weeks ago)
     Started: 12/31/2021 01:23:45 PM (6 weeks ago)
    Activity: 01/01/2022 01:23:45 AM (6 weeks ago)
    Finished: 12/31/2021 01:23:45 PM (6 weeks ago)
```

I find the 12 hour time format very confusing. Is it possible to use the 24 hour time format?

Here in source: https://github.com/tremc/tremc/blob/master/tremc#L2973-L2983

**Comment by MatanZ** [comment]
It depends on your locale settings. For me it displays time in 24 hours format, and displays the dates correctly.

You can replace `%X` in the line above the lines you highlighted with `%H:%M:%S` (twice) to get 24 hours format. But in general, I believe that following the locale is the appropriate behaviour.

**Comment by ilf** [comment]
@MatanZ: Thank you for your comment. You are correct, of course. This works as it should and setting `LC_TIME` is the correct approach. Sorry for not checking this. Closing this issue.
