### ISSUE TITLE
Compatibility with RPC 17

### ISSUE THREAD

**Issue by konstantin-morenko** [tremc/tremc#118]
I build transmission from GitHub sources, it has RPC version 17. Tremc says:

    Unsupported Transmission version: 3.00+ -- RPC protocol version: 17

I've changed line 59 to `RPC_VERSION_MAX = 17`. It seems working but I am not sure. Is it compatible with this version?

**Comment by MatanZ** [comment]
It is compatible. Nothing was removed from the protocol in this version, or modified in a way that breaks tremc. You can also use `-X` switch, instead of modifying the program.

**Comment by leg7** [comment]
The program should tell you that you can use the -X flag to bypass this error.
