### ISSUE TITLE
Unsupported Transmission version: 4.0.1

### ISSUE THREAD

**Issue by se7en-x230** [tremc/tremc#124]

**Comment by navapk** [comment]
I downgraded transmission to v3.0.0

**Comment by thexavier666** [comment]
Check #118 for solution or #58 for another type of solution

**Comment by se7en-x230** [comment]
Thanks -X sounds like the easiest fix

**Comment by pitsi** [comment]
How can I add any of the 3 options (`-X, --skip-version-check, --permissive`) to ~/.config/tremc/settings.cfg?
Adding one under `[Connection]` like so `permissive = True` has no results.

Debian testing/unstable x64, python 3.11.2 and tremc 0.93.

p.s. There is also a small issue with ratios etc now, but I will open a new issue report for that in the future.

**Comment by pitsi** [comment]
SInce no one has replied on my question yet, let me add something.

Adding (any of) these 2 variables under the `[Misc]` part of config.cfg makes no difference
```
skip-version-check = True
permissive = True

```

**Comment by gokberkgunes** [comment]
@pitsi, it seems from the source code it is not possible to set these settings through the configuration file. You can easily alias tremc in bashrc/zshrc as shown below to avoid your problem.

```sh
alias tremc="tremc -X"
```

**Comment by pitsi** [comment]
The 'permit-rpc-version-17' commit that was applied yesterday makes tremc work with transmission 4 without the -X parameter. Thank you :)

Honest question: how can someone find 'RPC_VERSION_MAX' from transmission's source or settings? Back when I first tried tremc on transmission 4.x, I wanted to change that, but i had no idea what to change it to... so I set it to 99 and it worked :D
