### ISSUE TITLE
auth from config fails when passing options to transmission-remote

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#18]
### Actual behavior
```
$ tremc -- -l
EXECUTING:
transmission-remote localhost:9091 -l --auth transmission:PASSWORD
RESPONSE:
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User�%GxHG�AG
```

### Expected behavior
it should work.

### Additional Comments
There are two reasons this fails:
* ~~Reading the password is not implemented.~~
~~The string "PASSWORD" is passed to `transmission-remote` just like that for no reason. So  that obviously won't work.~~
Looks like `cmd_print` is just for what gets printed in output.
```
        if config.get('Connection', 'username') and config.get('Connection', 'password'):
            cmd_print = cmd
            cmd_print.extend(['--auth', '%s:PASSWORD' % config.get('Connection', 'username')])
            print("EXECUTING:\n%s\nRESPONSE:" % ' '.join(cmd_print))
            cmd.extend(['--auth', '%s:%s' % (config.get('Connection', 'username'), config.get('Connection', 'password'))])
        else:
            print("EXECUTING:\n%s\nRESPONSE:" % ' '.join(cmd))
```

* Even if we read the password from config and pass it in that `cmd_print.extend` line, it still won't work. Apparently, `transmission-remote` requires `--auth` to be given before any other options. In other words:

This won't work:
```
transmission-remote -l --auth user:pass
```

This will work:
```
transmission-remote --auth user:pass -l
```

That seems to be all. It's just a matter of rearranging how `cmd` is built in the tremc code. I'm busy right now so I just wanted to document this. I'll try to get back on this later.

**Comment by gangelop** [comment]
On a sidenote, it might be better to use `--authenv` and `TR_AUTH` so that the password is not exposed in the cmdline of the process.

**Comment by louipc** [comment]
On Tue 10 Apr 2018 11:55 +0000, George Angelopoulos wrote:
> On a sidenote, it might be better to use `--authenv` and `TR_AUTH` so that the
> password is not exposed in the cmdline of the process.

I believe I have also received patches for this privately.
I have added them to a fix-auth branch for the time being.
I also see your pull request. Thank you.

**Comment by gangelop** [comment]
pull request updated.
