### ISSUE TITLE
tremc crashes with "_curses.error: addwstr() returned ERR" when terminal is less than 49 characters wide.

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#22]
It should gracefully exit with a more informative message instead.

```
Traceback (most recent call last):
  File "/bin/tremc", line 3711, in <module>
    Interface()
  File "/bin/tremc", line 985, in __init__
    self.run()
  File "/bin/tremc", line 1092, in run
    self.draw_stats()      # show global states
  File "/bin/tremc", line 2614, in draw_stats
    self.draw_torrents_stats()
  File "/bin/tremc", line 2645, in draw_torrents_stats
    self.screen.addstr("%d) " % paused, curses.A_REVERSE)
_curses.error: addwstr() returned ERR
```

**Comment by gangelop** [comment]
This is actually a regression (kind of...). In `transmission-remote-cli` I get "Terminal too small" instead of a crash, until the window is resized to a supported size at which point the interface appears again and it continues working. The code for this is still in tremc but there has been some change involving magic numbers.

In transmission-remote-cli we have:
```
    def get_screen_size(self):
        time.sleep(0.1) # prevents curses.error on rapid resizing
        while True:
            curses.endwin()
            self.screen.refresh()
            self.height, self.width = self.screen.getmaxyx()
            # Tracker list breaks if width smaller than 73
            if self.width < 73 or self.height < 16:
                self.screen.erase()
                self.screen.addstr(0,0, "Terminal too small", curses.A_REVERSE + curses.A_BOLD)
                time.sleep(1)
            else:
                break
        self.manage_layout()
```

and in tremc we have:
```
    def get_screen_size(self):
        time.sleep(0.1) # prevents curses.error on rapid resizing
        while True:
            curses.endwin()
            self.screen.refresh()
            self.height, self.width = self.screen.getmaxyx()
            # Tracker list breaks if width smaller than 40
            if self.width < 40 or self.height < 16:
                self.screen.erase()
                self.screen.addstr(0,0, "Terminal too small", curses.A_REVERSE + curses.A_BOLD)
                time.sleep(1)
            else:
                break
        self.manage_layout()
```
While in this specific case transmission-remote-cli correctly prints the error, it still relies on magic numbers and it's not clear what the assumptions behind these values are. It would be nice to solve this in a more reliable way, without magic numbers.

**Comment by gangelop** [comment]
It looks like the only change here is from Loui in 7d043805663863d854a591a3cbafed9e041cf584.
The commit message doesn't shed any light on the issue but I'm assuming that Loui must have had some good reason for this change and that he at least tested it.

@louipc Do you maybe remember why you set the minimum width to 40 instead of 73? Or do you at least remember if you tested it and it worked with a 40-character-wide terminal?

For me the minimum is 49. Bellow 49 it crashes.

**Comment by louipc** [comment]
On Wed 04 Jul 2018 11:06 -0700, George Angelopoulos wrote:
> @louipc Do you maybe remember why you set the minimum width to 40 instead of
> 73? Or do you at least remember if you tested it and it worked with
> a 40-character-wide terminal?
> 
> For me the minimum is 49. Bellow 49 it crashes.

Yeah that was my quick hack to allow a terminal smaller.
I dont remember that well, but yea it probably did crash when smaller than 40 so
I didnt bother to debug that.

**Comment by gangelop** [comment]
Ah ok. Thanks for the response. I think it would make sense to revert this then. But I would also like to find out and at least document why these specific minimum values are needed. I'll look into it...

**Comment by gangelop** [comment]
Actually...

It crashes with widths from 40 to 48. Anything bellow or above that works.
I've reverted the original commit and opened a new issue #28 to address this again.
