### ISSUE TITLE
progress percentages for files are not updated dynamically

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#26]
### Steps to reproduce:

* add a torrent
* go to the file list before the torrent is completed.
* Note the Progress percentage for files. Note the progress bar for the entire torrent.

### Actual behavior
Progress bar moves as usual but percentages for individual files do not change.

### Expected behavior
Percentages should be updated in real time just like the progress bar for the entire torrent.

**Comment by elundmark** [comment]
Still an issue for me in version 0.9.1

**Comment by MatanZ** [comment]
This is resolved in https://github.com/tremc/tremc/pull/60/commits/a111078a6a87bc59c875f39f6ab1762c6d56aa85
