### ISSUE TITLE
README: adns untested

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#33]
I don't want to say that we're releasing a [1.0.0](https://github.com/tremc/tremc/milestone/1) version and at the same time say we are providing some "untested" feature. That's dumb.

Either understand how it works, test it and stop saying it's untested or get rid of it.

**Comment by lebarondemerde** [comment]
Worked for me. Due to time and lack of downloading torrent at the moment I just had 1 peer, but for that one it worked.

FreeBSD 11.2-RELEASE
