### ISSUE TITLE
Seeding color?

### ISSUE THREAD

**Issue by elundmark** [tremc/tremc#48]
Seeding torrents only sometimes goes the color green. I've tried all sorts of terminals, and it only turns green _sometimes_.

It seems to depend on the torrent, and not by chance or the terminal.

Hard to reproduce I know, any ideas what it could be?

__Debian testing__
Compiled the latest git repo, as of 2019-12-22 22:53:17.
`transmission-daemon/testing,now 2.94-2+b2 amd64`

**Comment by louipc** [comment]
On Sun 22 Dec 2019 13:59 -0800, elundmark wrote:
> Seeding torrents only sometimes goes the color green. I've tried all sorts of
> terminals, and it only turns green _sometimes_.

Whats green? Background or text?

Impossible to diagnose like this.  Need more info like what is seed ratio, seed
limit, screenshot, copy of torrent file, etc, etc, etc

Background should be green if limit is unlimited or if ratio is above or equal
to limit.

**Comment by elundmark** [comment]
>  Background should be green if limit is unlimited or if ratio is above or equal to limit.

Oh, my mistake. In `transmission-remote-cli` I was used to seeding torrents _always_ having a green background, regardless of ration, or limits.
