### ISSUE TITLE
Progress bars do not support unlimited ratio correctly

### ISSUE THREAD

**Issue by KronK0321** [tremc/tremc#5]
## Description ##

The progress bars for torrents that have unlimited ratio specified behave in an odd manner. 

The progress bar for downloading torrents is accurate.
The progress bar for seeding torrents that have a ratio set is accurate. 

For seeding torrents that do not have a ratio set -- ie: have their seed ratio limit set to -1 -- the progress bar displays as if the torrent has a seed ratio set to the same as the global seed ratio.

## Steps to reproduce ##

Specify a global ratio. Say, 10.
Begin seeding a torrent that has less than a 10:1 ratio
Specify a seed ratio limit on that torrent of -1
Observe that the progress bar indicates the torrent is not done seeding

## Expected behaviour ##

The application tremc was based on, transmission-remote-cli, displays the progress bar at 100% complete. I expected tremc would display either 100% or 0%.

**Comment by louipc** [comment]
On Mon 03 Apr 2017 09:57 -0700, KronK0321 wrote:
> ## Description ##
>
> The progress bars for torrents that have unlimited ratio specified behave in an odd manner.
>
> The progress bar for downloading torrents is accurate.
> The progress bar for seeding torrents that have a ratio set is accurate.
>
> For seeding torrents that do not have a ratio set -- ie: have their seed ratio
> limit set to -1 -- the progress bar displays as if the torrent has a seed
> ratio set to the same as the global seed ratio.
>
> ## Steps to reproduce ##
>
> Specify a global ratio. Say, 10.
> Begin seeding a torrent that has less than a 10:1 ratio
> Specify a seed ratio limit on that torrent of -1
> Observe that the progress bar indicates the torrent is not done seeding
>
> ## Expected behaviour ##
>
> The application tremc was based on, transmission-remote-cli, displays the
> progress bar at 100% complete. I expected tremc would display either 100% or
> 0%.

Thanks for the nice bug report.
I was not able to replicate this behaviour though.
What version of python do you use?
I'm using 3.6.0 and actually a newer python seemed to fix some other bug.

**Comment by louipc** [comment]
On Mon 03 Apr 2017 09:57 -0700, KronK0321 wrote:
> ## Expected behaviour ##
>
> The application tremc was based on, transmission-remote-cli, displays the
> progress bar at 100% complete. I expected tremc would display either 100% or
> 0%.

Oh I see with Configuration 'torrentname_is_progressbar = True'. Thanks.

**Comment by KronK0321** [comment]
As I'm running Debian Jessie, the newest version of apt-installable python is Python 3.4.2. 

Sorry about that detail. Yes, I was referring to the progress bars behind the title on the main torrent list while Title is Progress Bar is set to yes.

Thanks!

**Comment by gangelop** [comment]
I can reproduce the issue on tremc, but I can also reproduce the same behavior on transmission-remote-cli (1e412a2).

If you get the correct, expected behavior on transmission-remote-cli, please let me know which version you are using.

This still needs to be fixed regardless.

**Comment by gangelop** [comment]
It's this ugly function that's doing it.

```
    def draw_torrentlist_title(self, torrent, focused, width, ypos):
        if (torrent['status'] == Transmission.STATUS_SEED
                and (self.stats['seedRatioLimited'] or torrent['seedRatioMode'] == 1)):
            limit = torrent['seedRatioLimit'] if torrent['seedRatioMode'] == 1 else self.stats['seedRatioLimit']
            if limit > 0:
                percentDone = min((torrent['uploadRatio'] * 100) / limit, 100)
            else:
                percentDone = 0
```

Thinking about how to rewrite it to both fix the bug and make it more readable.

**Comment by gangelop** [comment]
@KronK0321 If you still care about this, you might want to test the i5 branch a.k.a. commit 76cffc9.

If not and there aren't any other comments, I'll just merge it in a couple of days.

**Comment by KronK0321** [comment]
I can confirm the most recent master branch now exhibits the expected behaviour, thanks!

I'm not sure what the build number of my transmission-remote-cli is but it reports version 1.7.0 and appears to have identical behaviour to the latest tremc.

**Comment by KronK0321** [comment]
I tried transmission-remote-cli 1.7.1 via the link you provided. It has the same title-as-progress-bar behaviour that tremc used to have.

It has been a year since I initially reported this bug and it seems that I'm misremembering how transmission-remote-cli displayed the progress bars but here are my observations now:

transmission-remote-cli 1.7.0-1 is [the one available in my distro's package manager](https://packages.debian.org/stretch/transmission-remote-cli). It appears to provide a title-as-progress-bar for torrents in the "downloading" status only. With any of my torrents in "seeding" status, I can't get the title bar to display anything other than 100% no matter what I set that individual torrent's ratio as. I find this odd because I swear it used to  but I've been using tremc for so long I'm probably conflating the two programs.

transmission-remote-cli 1.7.1 (6a8e358) provides the title-as-progress-bar for torrents in both the "downloading" and "seeding" states. During seeding, the status bar percent-filled value for each torrent updates correctly when I change that torrent's seed ratio to any value other than -1. When set to -1, the progress bar uses the Global Seed Ratio Limit as its 100% value.

tremc (current latest) works the same as transmission-remote-cli 1.7.1 but when a torrent's seed ratio is set to -1, the progress bar is locked at 100% no matter what the Global Seed Ratio Limit is set to. I believe this to be optimal display behaviour.

**Comment by gangelop** [comment]
Excellent. Thanks for taking the time to re-check everything. I only started looking into tremc recently and since my observations and you original reported observations were different I was afraid I was missing something significant in the code.
It looks like we haven't missed anything now and the individal -1 combined with the global limit never worked correctly, until now. 👌
