### ISSUE TITLE
RPC version max out of range error <16

### ISSUE THREAD

**Issue by croyleje** [tremc/tremc#55]
RPC version error no longer works with transmission 3.0

**Comment by croyleje** [comment]
simply changing the RPC max version appears to work but the builds from AUR and clones wont work unless you manually edit just thought everyone would like a heads up

**Comment by vredesbyyrd** [comment]
Just ran into this on arch linux, thank you for the heads up.

**Comment by gangelop** [comment]
resolved in #41
