### ISSUE TITLE
Transmission 3.0 not supported

### ISSUE THREAD

**Issue by shadowlmd** [tremc/tremc#58]
Please whitelist transmission 3.0.

**Comment by kronikpillow** [comment]
yeah I seem to have the same problem now :(

**Comment by pitsi** [comment]
I have it too.
```
$ tremc
Unsupported Transmission version: 3.00 (bb6b5a062e) -- RPC protocol version: 16
Please install Transmission version 2.94 or lower.
```
I changed line 21 to
`TRNSM_VERSION_MAX = '3.00'`
and line 23 to
`RPC_VERSION_MAX = 16`
and it worked.

**Comment by Aarnar** [comment]
i changed 
`TRNSM_VERSION_MAX = '3.00'`
and 
`RPC_VERSION_MAX = 16`
but it didn't work.

**Comment by kronikpillow** [comment]
sorry huh? where are these changes supposed to go?

**Comment by pitsi** [comment]
@Aarnar 
Well, since my distro does not package tremc, I downloaded the file from here, saved it in my ~/bin and I use it from there, so patching it was really a 5 second task.

@kronikpillow 
What distro are you on or how did you install tremc?

**Comment by quite** [comment]
This change was suggested already in jan 2019 here #41. But apparently it odes not work perfectly. Maintainer seems to be somewhat absent...

**Comment by gangelop** [comment]
> Maintainer seems to be somewhat absent...

I am unfortunately somewhat absent and have limited access to a real computer. I will be back online after July 20th.

**Comment by pitsi** [comment]
I can wait till then. I have no other cli/tui client to use :P

**Comment by kronikpillow** [comment]
@pitsl im using Arch and installed via AUR

**Comment by pitsi** [comment]
@kronikpillow 
A quick and dirty way I can think is to edit tremc's executable, which probably is in /usr/bin/tremc and change the things I mention above.
If the path is wrong, please wait a couple of hours so I can ask a friend who uses arch.

**Comment by pitsi** [comment]
@kronikpillow 
Yeap, it is under /usr/bin/tremc as my friend confirmed.

**Comment by gangelop** [comment]
AUR package updated.
Please report if you  face any issues.
I've also proposed #59 to avoid this situation in the future.

Hopefully I'll be able to sneak back online in another two or three days for a short while if anything needs merging.
