### ISSUE TITLE
Invalid or corrupt torrent file

### ISSUE THREAD

**Issue by peaveyman** [tremc/tremc#6]
I've tried to add 2 different torrent files that were created by transmission and both times it tells me the file is invalid or corrupt. I can add them to transmission using transmission remote gui with no problem.

**Comment by peaveyman** [comment]
I also tried downloading the torrent and then adding it but get the same error.

**Comment by ian-s-mcb** [comment]
I also get this error. I cannot add any torrent files at the moment. Thankfully, magnet links still work.

**Comment by louipc** [comment]
Can you produce a problem torrent file? Thanks.

**Comment by ian-s-mcb** [comment]
http://releases.ubuntu.com/artful/ubuntu-17.10-desktop-amd64.iso.torrent

**Comment by louipc** [comment]
Hmm works for me. What version of transmission are you running?
I'm running transmission-cli 2.92 on archlinux.

Try adding the torrent on the command line after downloading the file with:
>transmission-remote -a ubuntu-17.10-desktop-amd64.iso.torrent

If that fails, I don't think its a bug in tremc.

**Comment by louipc** [comment]
I also just tried this again by giving tremc the url rather than downloading manually.
It still works fine for me.

**Comment by ian-s-mcb** [comment]
Adding the .torrent file via the transmission-remote command works. Adding the .torrent file in tremc using the URL works. But adding the .torrent in tremc using local path fails.

My first guess was that it's file permission issue, but I did some checking and that doesn't seem like the cause.

```bash
cp ubuntu-17.10-desktop-amd64.iso.torrent ubuntu.torrent
chmod 777 ubuntu.torrent
# Still unable to add ubuntu.torrent in tremc
```

I'm running transmission 2.92. In Ubuntu, the tools are spread across three packages (common, cli, daemon), and they are all version: 2.92-2ubuntu3.

**Comment by louipc** [comment]
Hmm very strange. Well at least theres a nice workaround with using url directly for now.
I'm too lazy to debug this myself at this time.

**Comment by ian-s-mcb** [comment]
No sweat. The workaround is fine for now.

**Comment by gangelop** [comment]
Ok. Here's where it goes South:

```
    def add_torrent(self, location):
        args = {}
        try:
            with  open(location, 'rb') as fp:
                args['metainfo'] = str(base64.b64encode(fp.read()))
        # If the file doesnt exist or we cant open it, then it is either a url or needs to
        # be open by the server
        except IOError:
            args['filename'] = location

        request = TransmissionRequest(self.host, self.port, self.path, 'torrent-add', 1, args)
        request.send_request()
        response = request.get_response()
        if response['result'] != 'success':
            return response['result']
        else:
            return ''
```

Specifically, something ins't working correctly with the metainfo argument. The transmission rpc-spec says we can use either "filename" OR "metainfo". If we remove the whole "try-except" and just leave the line "args['filename'] = location" line so that we give the transmission-daemon the file path and let it open it by itself, then it works.

Apparently there was a design choice made here to try and open the file ourselves and send the contents to the daemon through metainfo. I guess this makes sense if the daemon doesn't have access to the local filesystem. I'll try to look into this.

**Comment by gangelop** [comment]
Found it. A victim of 2to3. patch incoming...
