### ISSUE TITLE
underscore and subsequent characters are omitted from "Select location" dialog

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#76]
When filtering by location, in the "Select location" dialog, if a location has an underscore, the underscore and the subsequent characters are not printed. For example, the location `~/os_images` will be printed as `~/os`.

**Comment by MatanZ** [comment]
It is clear how this happens - it will probably be true also for filtering labels, and in general where the strings come from the user and we cannot ensure they have no _.

**Comment by gangelop** [comment]
thanks!
