### ISSUE TITLE
sorting by tracker through the menus (s > k) triggers a crash

### ISSUE THREAD

**Issue by gangelop** [tremc/tremc#84]
sorting by tracker through the menus (s > k) triggers a crash.
`tremc` exits silently with `0` so this is some exception which is being caught.
In `0.9.2` the Traceback is:

```
Traceback (most recent call last):
File "./tremc", line 3728, in <module>
Interface()
File "./tremc", line 994, in __init__
self.run()
File "./tremc", line 1095, in run
self.draw_torrent_list()
File "./tremc", line 1858, in draw_torrent_list
self.torrents = server.get_torrent_list(self.sort_orders)
File "./tremc", line 521, in get_torrent_list
self.torrent_cache.sort(key=lambda x: sort_value(x[sort_order['name']]),
TypeError: '<' not supported between instances of 'NoneType' and 'str'                                         
```
It's unclear what when was the last time this worked.

**Comment by MatanZ** [comment]
In general, to see the output, use something like 
`tremc -d 2>> tremc.log`

Do you have trackerless torrents? Does it happen every time? It did not crash for me in a few attempts.

**Comment by gangelop** [comment]
Yes, it's the trackerless torrent which causes it, for example Arch Linux iso:
```
magnet:?xt=urn:btih:db56a13a6555179990837759ca27274d0be49aca&dn=archlinux-2020.09.01-x86%5F64.iso
```
